INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, CIF, STATUS , CREATED_ON ) values ('Test','Customer 1', '00001','ACTIVE',CURRENT_TIMESTAMP());
INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, CIF, STATUS , CREATED_ON ) values ('Test','Customer 2', '00002','ACTIVE',CURRENT_TIMESTAMP());

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, IBAN , ACCOUNT_TYPE, ACTIVE, CURRENCY, ACCOUNT_BALANCE, CUSTOMER_ID, CREATED_ON )
 values ('1234','0001234','SA',0,'USD',20000,1,CURRENT_TIMESTAMP()) ;
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, IBAN , ACCOUNT_TYPE, ACTIVE, CURRENCY, ACCOUNT_BALANCE, CUSTOMER_ID, CREATED_ON )
 values ('4567','0001234','SA',0,'USD',40000,1,CURRENT_TIMESTAMP()) ;
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, IBAN , ACCOUNT_TYPE, ACTIVE, CURRENCY, ACCOUNT_BALANCE, CUSTOMER_ID, CREATED_ON )
 values ('7890','0007890','SA',0,'USD',10000,2,CURRENT_TIMESTAMP()) ;